// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddDevices(arg1:Array<backend.Device>):Promise<Array<backend.Device>>;

export function BrowseDirectory(arg1:string):Promise<string>;

export function CancelScan():Promise<void>;

export function FindBinary(arg1:string):Promise<string>;

export function LoadSettings():Promise<backend.Settings>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<string>;

export function RemoveDevice(arg1:string):Promise<Array<backend.Device>>;

export function RenameDevice(arg1:string,arg2:string):Promise<Array<backend.Device>>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function ScanDevices():Promise<Array<backend.Device>>;

export function SetActiveDevice(arg1:string):Promise<void>;

export function StartScan(arg1:backend.Settings):Promise<void>;
