// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevices(arg1) {
  return window['go']['backend']['App']['AddDevices'](arg1);
}

export function BrowseDirectory(arg1) {
  return window['go']['backend']['App']['BrowseDirectory'](arg1);
}

export function CancelScan() {
  return window['go']['backend']['App']['CancelScan']();
}

export function FindBinary(arg1) {
  return window['go']['backend']['App']['FindBinary'](arg1);
}

export function LoadSettings() {
  return window['go']['backend']['App']['LoadSettings']();
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['backend']['App']['OpenFolder'](arg1);
}

export function RemoveDevice(arg1) {
  return window['go']['backend']['App']['RemoveDevice'](arg1);
}

export function RenameDevice(arg1, arg2) {
  return window['go']['backend']['App']['RenameDevice'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function ScanDevices() {
  return window['go']['backend']['App']['ScanDevices']();
}

export function SetActiveDevice(arg1) {
  return window['go']['backend']['App']['SetActiveDevice'](arg1);
}

export function StartScan(arg1) {
  return window['go']['backend']['App']['StartScan'](arg1);
}
